### ISSUE TITLE
Multiple users?

### ISSUE THREAD

**Issue by bytes-max** [gentoo-root/telegram-tracker#10]
Is it possible to add a multiple users feature, maybe seperated by `,`?

**Comment by gentoo-root** [comment]
Duplicate of #9. Just run multiple parallel instances of the script.

**Comment by bytes-max** [comment]
Its not possible to do this. This is the error output:
```

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hdd3/Development/teletrack/track/__main__.py", line 47, in <module>
    client.start()
  File "/home/user/.local/lib/python3.6/site-packages/telethon/client/auth.py", line 132, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.6/site-packages/telethon/client/auth.py", line 139, in _start
    await self.connect()
  File "/home/user/.local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 483, in connect
    self.session.auth_key = self._sender.auth_key
  File "/home/user/.local/lib/python3.6/site-packages/telethon/sessions/sqlite.py", line 175, in auth_key
    self._update_session_table()
  File "/home/user/.local/lib/python3.6/site-packages/telethon/sessions/sqlite.py", line 189, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked

```

**Comment by gentoo-root** [comment]
Yeah, that's correct, the underlying library (telethon) uses an sqlite database to store the session, and it doesn't support multiple connections. I'll have to modify the script to use another backend for sessions.

In the meanwhile, the workaround is to cd to a different directory before running the script, so that the session file is created there.
