### ISSUE TITLE
error

### ISSUE THREAD

**Issue by monicadcintron** [gentoo-root/telegram-tracker#13]
python3 -m track '+380991234567'
Please enter your phone (or bot token): +1 ***********   
Please enter the code you received: 93166
Signed in successfully as 𝓗𝓪𝓻𝓪 𝓟𝓮𝓽𝓻𝓸𝓼𝓲𝓪𝓷
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Desktop/telegram-tracker/track/__main__.py", line 57, in <module>
    contact = client.get_entity(contact_id)
  File "/usr/local/lib/python3.8/dist-packages/telethon/sync.py", line 35, in syncified
    else asyncio.get_event_loop().run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 203, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/users.py", line 383, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "+380991234567"

**Comment by gentoo-root** [comment]
+380991234567 is not a real existing account, it's just an example, you should use the real number that you want to track.

**Comment by lorenzoromani1983** [comment]
but I am getting the same error, with an existing account. Is the code still working?
