### ISSUE TITLE
Cannot find any entity corresponding to 

### ISSUE THREAD

**Issue by karopass** [gentoo-root/telegram-tracker#3]
Hi!
This is giving me error like below

C:\Users\Administrator\Downloads\telegram-tracker-master\telegram-tracker-master>python -m track '+91XXXXXXXXXX'
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Downloads\telegram-tracker-master\telegram-tracker-master\track\__main__.py", line 50, in <module>
    contact = client.get_entity(contact_id)
  File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2553, in get_entity
    for x in inputs
  File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2553, in <listcomp>
    for x in inputs
  File "C:\ProgramData\Miniconda3\lib\site-packages\telethon\telegram_client.py", line 2606, in _get_entity_from_string
    'Cannot find any entity corresponding to "{}"'.format(string)
ValueError: Cannot find any entity corresponding to "'+91XXXXXXXXXX'"

Thanks

**Comment by karopass** [comment]
Hi!
I have solved using number as int like +91XXXXXXXXXX.
Thanks
