### ISSUE TITLE
UserMethods.get_entity

### ISSUE THREAD

**Issue by odetoyama** [gentoo-root/telegram-tracker#4]
Hi,
I try to run the script like this
`py -3.7 -m track 'me'`
and result is
`C:\Users\DynEd\Downloads\Compressed\telegram-tracker-master>py -3.7 -m track 'me'
Traceback (most recent call last):
  File "C:\Users\DynEd\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\DynEd\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DynEd\Downloads\Compressed\telegram-tracker-master\track\__main__.py", line 73, in <module>
    if isinstance(contact.status, UserMethods):
AttributeError: 'coroutine' object has no attribute 'status'
sys:1: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited`

I'm not sure what really happened. Maybe this script is no longer supported by the current version of Telethon or Telegram API?

**Comment by gentoo-root** [comment]
Added two fixes for the newer Telethon version.
